#!/usr/bin/env python3
"""Generate three weeks of synthetic agent history for the demo.

**SYNTHETIC DATA.  NOTHING IN THE OUTPUT WAS EVER SENT TO A MODEL.**

This script invents a fortnight-and-a-half of "the agent coded all day" sessions
so the demo has a history to show: which tasks were attempted, how many requests
each one took, how many the router moved to the cheap model, and what the same
traffic would have cost on the strong model alone.  It writes

    demo/history/agent-3weeks.db     request log, same schema `tamias serve` writes
    demo/history/agent-3weeks.json   per-session and per-day summary
    demo/history/SUMMARY.md          the same summary as a table

and every file it produces says SYNTHETIC on the face of it.

What makes it a *demo* of tamias rather than a made-up table:

* the request rows are written by the real :class:`tamias.store.Store`, so
  ``tamias report``, ``tamias.dashboard`` and every other reader see a normal
  log and need no special case;
* the routing decisions come from the real :func:`tamias.router.decide` fed the
  real message shapes an agent session produces, so the SWITCH/STAY mix is the
  router's own behaviour, not a coin flip;
* the costs come from the real :func:`tamias.pricing.compute_cost` against
  ``prices.simulated.toml``, whose ``simulated = true`` is what stamps
  ``SIMULATED PRICES, NOT REAL SAVINGS`` on every line ``tamias report``
  prints.  The rates are invented, the arithmetic is not;
* token counts are derived from the message bytes the script actually builds
  (``ceil(chars / 4)``) with prefix caching modelled as "the context the previous
  request already had", so input, cached and output counts agree with each other
  instead of being three unrelated random numbers.

Usage::

    .venv/bin/python demo/make_history.py
    .venv/bin/python demo/make_history.py --end 2026-10-05 --days 21 --seed 7

The output is deterministic for a given ``--seed``/``--days``/``--end``, so a
regeneration reproduces the numbers quoted in the demo.
"""

from __future__ import annotations

import argparse
import json
import math
import random
import sys
from dataclasses import dataclass
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Any

from tamias.pricing import PriceSheet, compute_cost, load_price_sheet
from tamias.router import RouterConfig, decide
from tamias.store import Store
from tamias.types import CostBreakdown, Decision, SessionState, Usage

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUT = REPO_ROOT / "demo" / "history"
DEFAULT_PRICES = REPO_ROOT / "prices.simulated.toml"

STRONG = "strong"
CHEAP = "cheap"
MIN_GAP = 3
CONFIG = RouterConfig(cheap_model=CHEAP, strong_model=STRONG, min_gap=MIN_GAP)
PRICE_SHEET_LABEL = "prices.simulated.toml"

SYNTHETIC_NOTE = (
    "SYNTHETIC DEMO DATA: no request in this file was ever sent to a model. "
    "Generated by demo/make_history.py."
)

# --------------------------------------------------------------------------
# What the agent worked on.  40 sessions cover a 21-day window at 1-2 a day.
# --------------------------------------------------------------------------

TASKS: tuple[tuple[str, tuple[str, ...], str], ...] = (
    ("fix flaky retry test in billing", ("billing/retry.py", "tests/test_retry.py"), "9/9 passed"),
    (
        "add cursor pagination to /users",
        ("api/users.py", "api/paging.py", "tests/test_users.py"),
        "14/14 passed",
    ),
    (
        "migrate settings to frozen dataclasses",
        ("config/settings.py", "config/loader.py"),
        "11/11 passed",
    ),
    (
        "repair broken CSV export quoting",
        ("export/csv_writer.py", "tests/test_csv.py"),
        "6/6 passed",
    ),
    (
        "tighten N+1 queries in the report view",
        ("reports/views.py", "reports/sql.py"),
        "8/8 passed",
    ),
    (
        "split the 900-line scheduler module",
        ("jobs/scheduler.py", "jobs/queue.py", "jobs/locks.py"),
        "21/21 passed",
    ),
    (
        "handle NULL currency in invoice rows",
        ("billing/invoices.py", "tests/test_invoices.py"),
        "12/12 passed",
    ),
    (
        "add idempotency keys to the pay endpoint",
        ("api/pay.py", "billing/idempotency.py"),
        "17/17 passed",
    ),
    (
        "fix timezone drift in the nightly job",
        ("jobs/nightly.py", "tests/test_nightly.py"),
        "10/10 passed",
    ),
    (
        "type-annotate the ingestion pipeline",
        ("ingest/pipeline.py", "ingest/parser.py"),
        "15/15 passed",
    ),
    (
        "make the cache stampede test deterministic",
        ("cache/locks.py", "tests/test_cache.py"),
        "7/7 passed",
    ),
    ("replace the hand-rolled JSON merge", ("util/merge.py", "api/patch.py"), "13/13 passed"),
    (
        "fix off-by-one in pagination cursors",
        ("api/paging.py", "tests/test_paging.py"),
        "9/9 passed",
    ),
    ("backfill missing audit rows", ("audit/backfill.py", "audit/schema.sql"), "5/5 passed"),
    ("cut the cold-start import time in half", ("app/boot.py", "app/lazy.py"), "12/12 passed"),
    (
        "repair the flaky websocket reconnect",
        ("realtime/socket.py", "tests/test_socket.py"),
        "8/8 passed",
    ),
    ("add a read-replica failover path", ("db/failover.py", "db/pool.py"), "16/16 passed"),
    ("fix rounding on split invoices", ("billing/split.py", "tests/test_split.py"), "11/11 passed"),
    ("dedupe webhook deliveries", ("webhooks/dedupe.py", "webhooks/handler.py"), "10/10 passed"),
    ("port the diff engine to a single pass", ("diff/engine.py", "diff/hunks.py"), "18/18 passed"),
    (
        "fix memory leak in the stream reader",
        ("realtime/stream.py", "tests/test_stream.py"),
        "7/7 passed",
    ),
    ("add compound index for the hot query", ("db/indexes.sql", "reports/sql.py"), "6/6 passed"),
    ("make the feature-flag roll-out safe", ("flags/rollout.py", "flags/gates.py"), "14/14 passed"),
    (
        "repair broken UTF-8 handling in imports",
        ("import/encoding.py", "tests/test_import.py"),
        "9/9 passed",
    ),
    (
        "split the monolith client into modules",
        ("client/api.py", "client/auth.py", "client/retry.py"),
        "23/23 passed",
    ),
    ("fix stale cache on profile update", ("cache/profile.py", "api/profile.py"), "8/8 passed"),
    (
        "add a rate limiter to the public API",
        ("api/limits.py", "api/middleware.py"),
        "19/19 passed",
    ),
    (
        "repair the broken retry-after header",
        ("http/retry_after.py", "tests/test_headers.py"),
        "7/7 passed",
    ),
    ("normalise the search index build", ("search/index.py", "search/tokenize.py"), "12/12 passed"),
    (
        "fix duplicate rows in the daily rollup",
        ("reports/rollup.py", "tests/test_rollup.py"),
        "10/10 passed",
    ),
    ("make the migration runner resumable", ("db/migrate.py", "db/lock.py"), "15/15 passed"),
    ("fix the JSON payload truncation bug", ("http/body.py", "tests/test_body.py"), "9/9 passed"),
    ("add structured logging to the worker", ("worker/log.py", "worker/runner.py"), "13/13 passed"),
    (
        "repair the broken auth token refresh",
        ("auth/refresh.py", "tests/test_auth.py"),
        "11/11 passed",
    ),
    ("cut duplicate file reads in the loader", ("loader/read.py", "loader/cache.py"), "8/8 passed"),
    (
        "fix the checkpointer's crash on restart",
        ("jobs/checkpoint.py", "tests/test_ckpt.py"),
        "12/12 passed",
    ),
    ("add a schema check to the CI step", ("ci/schema_check.py", "ci/pipeline.yml"), "6/6 passed"),
    (
        "repair mangled multi-part uploads",
        ("upload/multipart.py", "tests/test_upload.py"),
        "10/10 passed",
    ),
    ("refactor the permissions check", ("auth/perm.py", "auth/guards.py"), "16/16 passed"),
    (
        "fix the deadlock in the job sweeper",
        ("jobs/sweeper.py", "tests/test_sweeper.py"),
        "9/9 passed",
    ),
)

EASY_TOOLS = ("bash", "read", "grep", "ls", "glob")
HARD_TOOLS = ("edit_file", "write")

Bash_PASS = "$ pytest -q\n{passed} passed in {seconds:.2f}s"
Bash_GREP = "$ grep -rn '{needle}' src/\n{hits}"
Bash_LS = "$ ls -la src/\n{listing}"
Bash_SEED = "$ python -m pytest tests/ -x -q"


@dataclass(frozen=True, slots=True)
class Turn:
    """One request the invented agent session makes, in order."""

    kind: str  # "user" | "easy" | "hard" | "error"
    tool: str


@dataclass(frozen=True, slots=True)
class Logged:
    """A row the summary is built from, before it reaches the Store."""

    session_id: str
    ts: str
    decision: Decision
    model_used: str
    usage: Usage
    cost_usd: float | None
    latency_ms: int


# --------------------------------------------------------------------------
# Turn plans
# --------------------------------------------------------------------------


def plan_turns(rng: random.Random, turns: int) -> list[Turn]:
    """A session shaped like a real coding loop: look, change, run the tests.

    The loop is what makes the router produce a striped timeline.  Reading and
    grepping are easy-tool turns the router may switch; the edit is not; the
    test run is easy again but often comes back red, and a red run is exactly
    what rule 2 keeps on the strong model.
    """
    plan = [Turn("user", "")]
    while len(plan) < turns:
        # Reading and grepping are the cheap-tool turns; there are always two
        # of them before a change, and the test run after it is easy too.
        plan.append(Turn("easy", rng.choice(EASY_TOOLS)))
        plan.append(Turn("easy", rng.choice(EASY_TOOLS)))
        plan.append(Turn("hard", rng.choice(HARD_TOOLS)))
        if rng.random() < 0.35:
            plan.append(Turn("error", "bash"))
        plan.append(Turn("easy", "bash"))
        if rng.random() < 0.5:
            plan.append(Turn("easy", rng.choice(("grep", "glob"))))
    return plan[:turns]


# --------------------------------------------------------------------------
# Message shapes -- the same shapes dry_run_client.py sends, because that is
# what the router branches on.
# --------------------------------------------------------------------------


def _source_lines(rng: random.Random, lines: int) -> str:
    samples = (
        "def {name}({args}):\n    {body}\n",
        "class {name}:\n    def __init__(self, store):\n        self.store = store\n",
        '    assert {left} == {right}, f"{{left}} != {{right}}"\n',
        "# {name}: regenerated by the build\n",
    )
    out = []
    for _ in range(lines):
        template = rng.choice(samples)
        out.append(
            template.format(
                name=rng.choice(("parse", "render", "fetch", "merge", "validate", "retry")),
                args=rng.choice(("value", "payload, raw", "rows, limit=100", "key")),
                body=rng.choice(("return value", "raise ValueError(key)", "self.store.put(value)")),
                left=rng.choice(("total", "len(rows)", "status")),
                right=rng.choice(("0", "len(rows)", '"ok"')),
            )
        )
    return "".join(out)


def _tool_payload(rng: random.Random, turn: Turn, task: str) -> str:
    """The tool result text.  Its size is what grows the context window."""
    if turn.kind == "error":
        return (
            "Traceback (most recent call last):\n"
            f'  File "tests/test_{task.split()[0]}.py", line 12, in test_flow\n'
            "    assert result.ok is True\n"
            "AssertionError: assert False is True\n"
            "FAILED tests/test_flow.py::test_flow - AssertionError\n"
        )
    if turn.tool == "read":
        return _source_lines(rng, rng.randint(60, 320))
    if turn.tool == "grep":
        return "\n".join(
            f"src/{rng.choice(('api', 'jobs', 'billing', 'cache'))}/"
            f"{rng.choice(('views', 'runner', 'ledger', 'lock'))}.py:{rng.randint(10, 400)}:"
            f"    {rng.choice(('result = fn(value)', 'if not rows: return', 'log.info(key)'))}"
            for _ in range(rng.randint(8, 60))
        )
    if turn.tool == "ls":
        return "\n".join(
            f"{rng.choice(('-rw-r--r--', 'drwxr-xr-x'))} 1 krish krish {rng.randint(400, 90000)} "
            f"{rng.choice(('app.py', 'test_flow.py', 'index.sql', 'runner.py'))}"
            for _ in range(rng.randint(5, 40))
        )
    if turn.tool == "glob":
        return "\n".join(
            f"src/pkg/{rng.choice(('a', 'b', 'c', 'd'))}_{rng.randint(1, 9)}.py"
            for _ in range(rng.randint(6, 30))
        )
    if turn.tool == "bash":
        failed = "$ python -m pytest tests/ -q\n"
        failed += (
            f"{rng.randint(1, 4)} failed, {rng.randint(2, 30)} passed "
            f"in {rng.uniform(0.5, 5.0):.2f}s"
        )
        return rng.choice(
            (
                Bash_PASS.format(passed=rng.randint(6, 40), seconds=rng.uniform(0.4, 6.0)),
                "$ ruff check src/\nAll checks passed!",
                Bash_SEED,
                failed,
                Bash_GREP.format(
                    needle=rng.choice(("TODO", "raise NotImplementedError", "session_id")),
                    hits="\n".join(
                        f"src/{rng.choice(('api', 'jobs'))}/{rng.choice(('views', 'runner'))}.py:"
                        f"{rng.randint(10, 300)}:{rng.choice(('# TODO: split this', 'pass'))}"
                        for _ in range(rng.randint(3, 20))
                    ),
                ),
                Bash_LS.format(
                    listing="\n".join(
                        f"-rw-r--r-- 1 krish krish {rng.randint(900, 40000)} "
                        f"{rng.choice(('main.py', 'schema.py', 'test_api.py'))}"
                        for _ in range(rng.randint(4, 25))
                    )
                ),
            )
        )
    # edit_file / write: the change landed.
    return f"applied patch to {turn.tool} ({rng.randint(1, 3)} file(s) changed)"


def _assistant_payload(rng: random.Random, turn: Turn) -> str:
    """The assistant message: a plan, a tool call, or the patch it wrote."""
    if turn.kind == "user":
        return (
            "Reading the failing test first, then I'll make the smallest change that "
            "makes it pass and re-run the suite.\n"
        )
    if turn.kind == "error":
        return (
            "The assertion is wrong about the null case: the parser returns None before "
            "the coercion runs. I'll move the coercion ahead of the check and add a test.\n"
        )
    if turn.kind == "hard":
        return _source_lines(rng, rng.randint(12, 90))
    return rng.choice(
        (
            "Running the suite again.\n",
            "That file does not own this; checking the caller.\n",
            "Found it -- the guard is in the caller.\n",
            "Keeping the change small; no schema edit needed.\n",
        )
    )


def _assistant_message(rng: random.Random, turn: Turn, call_id: str) -> dict[str, Any]:
    if turn.kind == "user":
        return {"role": "assistant", "content": _assistant_payload(rng, turn)}
    return {
        "role": "assistant",
        "content": None,
        "tool_calls": [
            {
                "id": call_id,
                "type": "function",
                "function": {
                    "name": turn.tool,
                    "arguments": _assistant_payload(rng, turn),
                },
            }
        ],
    }


def _chars(value: Any) -> int:
    return len(json.dumps(value, ensure_ascii=False))


def _tokens(chars: int) -> int:
    """Token count for a byte length: the usual ~4 chars per token, rounded up.

    Rounded up, never down: an estimate that reads high is a demo that admits
    it is an estimate; one that reads low claims more precision than a
    character count can give.
    """
    return max(1, math.ceil(chars / 4))


# --------------------------------------------------------------------------
# One session
# --------------------------------------------------------------------------


def build_session(
    rng: random.Random,
    sheet: PriceSheet,
    task: str,
    session_id: str,
    day: date,
    start_hour: int,
    turns: int,
) -> list[Logged]:
    """Run one invented session through the real router and the real pricer."""
    plan = plan_turns(rng, turns)
    messages: list[dict[str, Any]] = []
    current_model = STRONG
    clock = datetime(day.year, day.month, day.day, start_hour, rng.randint(0, 40), 0)
    previous_input_tokens = 0
    out: list[Logged] = []

    for index, turn in enumerate(plan):
        if turn.kind == "user":
            messages.append({"role": "user", "content": task})
        else:
            call_id = f"call_{session_id}_{index}"
            messages.append(_assistant_message(rng, turn, call_id))
            messages.append(
                {
                    "role": "tool",
                    "tool_call_id": call_id,
                    "name": turn.tool,
                    "content": _tool_payload(rng, turn, task),
                }
            )

        decision = decide(
            {"model": STRONG, "messages": messages},
            SessionState(session_id=session_id, request_index=index, current_model=current_model),
            CONFIG,
        )
        model_used = decision.target_model if decision.action == "SWITCH" else STRONG
        current_model = model_used

        input_tokens = _tokens(_chars(messages))
        # A prefix cache serves what the previous request had already seen, so
        # the cached count is last turn's input and never more than this one's.
        cached = min(previous_input_tokens, input_tokens) if index >= 2 else 0
        output_tokens = _tokens(_chars(messages[-1])) + rng.randint(10, 180)
        previous_input_tokens = input_tokens

        usage = Usage(
            input_tokens=input_tokens,
            output_tokens=output_tokens,
            cached_input_tokens=cached,
            cache_write_tokens=0,
        )
        cost = compute_cost(model_used, usage, sheet)
        clock += timedelta(seconds=rng.randint(8, 120))
        out.append(
            Logged(
                session_id=session_id,
                ts=clock.isoformat(sep=" "),
                decision=decision,
                model_used=model_used,
                usage=usage,
                cost_usd=cost.usd,
                latency_ms=rng.randint(250, 9000)
                if model_used == STRONG
                else rng.randint(120, 2400),
            )
        )
    return out


# --------------------------------------------------------------------------
# The window
# --------------------------------------------------------------------------


def sessions_per_day(day: date) -> int:
    """Two a day on weekdays, one at the weekend: busy, not impossible."""
    return 1 if day.weekday() >= 5 else 2


def build_history(
    end: date,
    days: int,
    seed: int,
    sheet: PriceSheet,
) -> tuple[list[Logged], dict[str, Any]]:
    """Build every session in the window and summarise it."""
    rng = random.Random(seed)
    start = end - timedelta(days=days - 1)
    rows: list[Logged] = []
    sessions: list[dict[str, Any]] = []
    per_day: dict[str, dict[str, Any]] = {}

    for offset in range(days):
        day = start + timedelta(days=offset)
        for slot in range(sessions_per_day(day)):
            task, files, result = TASKS[(offset * 2 + slot) % len(TASKS)]
            session_id = f"{day.isoformat()}-{task.replace(' ', '-')[:40]}-{slot + 1}"
            count = rng.randint(18, 46)
            session_rows = build_session(
                rng,
                sheet,
                task=task,
                session_id=session_id,
                day=day,
                start_hour=9 + slot * 4,
                turns=count,
            )
            rows.extend(session_rows)
            sessions.append(_session_summary(session_rows, sheet, day, task, files, result))

            bucket = per_day.setdefault(
                day.isoformat(),
                {
                    "date": day.isoformat(),
                    "sessions": 0,
                    "requests": 0,
                    "switches": 0,
                    "saving_usd": 0.0,
                },
            )
            bucket["sessions"] += 1
            bucket["requests"] += len(session_rows)
            bucket["switches"] += sum(1 for r in session_rows if r.decision.action == "SWITCH")
            bucket["saving_usd"] += _saving_of(session_rows, sheet)

    summary = {
        "note": SYNTHETIC_NOTE,
        "generator": "demo/make_history.py",
        "seed": seed,
        "window": {"start": start.isoformat(), "end": end.isoformat(), "days": days},
        "price_sheet": {
            "path": PRICE_SHEET_LABEL,
            "simulated": sheet.simulated,
            "date": sheet.date,
        },
        "totals": _totals(sessions, rows, sheet),
        "weeks": _weeks(sessions),
        "days": [per_day[key] for key in sorted(per_day)],
        "sessions": sessions,
    }
    return rows, summary


def _price_of(model: str, usage: Usage, sheet: PriceSheet) -> float:
    usd = compute_cost(model, usage, sheet).usd
    if usd is None:
        raise ValueError(f"cannot price {model} with sheet {sheet.date}")
    return usd


def _saving_of(rows: list[Logged], sheet: PriceSheet) -> float:
    strong = sum(_price_of(STRONG, r.usage, sheet) for r in rows)
    actual = sum(_price_of(r.model_used, r.usage, sheet) for r in rows)
    return strong - actual


def _session_summary(
    rows: list[Logged],
    sheet: PriceSheet,
    day: date,
    task: str,
    files: tuple[str, ...],
    result: str,
) -> dict[str, Any]:
    strong = sum(_price_of(STRONG, r.usage, sheet) for r in rows)
    actual = sum(_price_of(r.model_used, r.usage, sheet) for r in rows)
    switches = sum(1 for r in rows if r.decision.action == "SWITCH")
    return {
        "date": day.isoformat(),
        "task": task,
        "files": list(files),
        "result": result,
        "session_id": rows[0].session_id,
        "requests": len(rows),
        "switches": switches,
        "cheap_requests": sum(1 for r in rows if r.model_used == CHEAP),
        "input_tokens": sum(r.usage.input_tokens or 0 for r in rows),
        "output_tokens": sum(r.usage.output_tokens or 0 for r in rows),
        "cached_input_tokens": sum(r.usage.cached_input_tokens or 0 for r in rows),
        "all_strong_usd": round(strong, 6),
        "actual_mix_usd": round(actual, 6),
        "saving_usd": round(strong - actual, 6),
        "saving_pct": round(100.0 * (strong - actual) / strong, 2) if strong else None,
        "first_ts": rows[0].ts,
        "last_ts": rows[-1].ts,
    }


def _totals(
    sessions: list[dict[str, Any]],
    rows: list[Logged],
    sheet: PriceSheet,
) -> dict[str, Any]:
    strong = sum(_price_of(STRONG, r.usage, sheet) for r in rows)
    actual = sum(_price_of(r.model_used, r.usage, sheet) for r in rows)
    return {
        "sessions": len(sessions),
        "requests": len(rows),
        "switches": sum(1 for r in rows if r.decision.action == "SWITCH"),
        "cheap_requests": sum(1 for r in rows if r.model_used == CHEAP),
        "input_tokens": sum(r.usage.input_tokens or 0 for r in rows),
        "output_tokens": sum(r.usage.output_tokens or 0 for r in rows),
        "cached_input_tokens": sum(r.usage.cached_input_tokens or 0 for r in rows),
        "all_strong_usd": round(strong, 6),
        "actual_mix_usd": round(actual, 6),
        "saving_usd": round(strong - actual, 6),
        "saving_pct": round(100.0 * (strong - actual) / strong, 2) if strong else None,
        "tasks_completed": len(sessions),
        "decisions": _decision_counts(rows),
    }


def _decision_counts(rows: list[Logged]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for row in rows:
        counts[row.decision.reason] = counts.get(row.decision.reason, 0) + 1
    return dict(sorted(counts.items(), key=lambda item: (-item[1], item[0])))


def _weeks(sessions: list[dict[str, Any]]) -> list[dict[str, Any]]:
    buckets: dict[str, dict[str, Any]] = {}
    for session in sessions:
        iso = date.fromisoformat(session["date"]).isocalendar()
        key = f"{iso[0]}-W{iso[1]:02d}"
        bucket = buckets.setdefault(
            key,
            {
                "week": key,
                "sessions": 0,
                "requests": 0,
                "switches": 0,
                "all_strong_usd": 0.0,
                "actual_mix_usd": 0.0,
                "saving_usd": 0.0,
            },
        )
        bucket["sessions"] += 1
        bucket["requests"] += session["requests"]
        bucket["switches"] += session["switches"]
        bucket["all_strong_usd"] += session["all_strong_usd"]
        bucket["actual_mix_usd"] += session["actual_mix_usd"]
        bucket["saving_usd"] += session["saving_usd"]
    out = []
    for key in sorted(buckets):
        bucket = buckets[key]
        strong = bucket["all_strong_usd"]
        bucket["saving_usd"] = round(bucket["saving_usd"], 6)
        bucket["all_strong_usd"] = round(strong, 6)
        bucket["actual_mix_usd"] = round(bucket["actual_mix_usd"], 6)
        bucket["saving_pct"] = round(100.0 * bucket["saving_usd"] / strong, 2) if strong else None
        out.append(bucket)
    return out


# --------------------------------------------------------------------------
# Writers
# --------------------------------------------------------------------------


def write_log(path: Path, rows: list[Logged], sheet: PriceSheet) -> None:
    """Write the request log with the real Store, stamped simulated."""
    if path.exists():
        path.unlink()
    store = Store(path)
    try:
        for row in rows:
            store.log_request(
                ts=row.ts,
                session_id=row.session_id,
                model_requested=STRONG,
                model_used=row.model_used,
                usage=row.usage,
                cost=CostBreakdown(
                    usd=row.cost_usd,
                    formula="synthetic: priced by demo/make_history.py with tamias.pricing",
                    price_sheet_date=sheet.date,
                ),
                latency_ms=row.latency_ms,
                status="ok",
                decision=row.decision,
                price_sheet=PRICE_SHEET_LABEL,
                price_simulated=True,
            )
    finally:
        store.close()


def render_summary_markdown(summary: dict[str, Any]) -> str:
    totals = summary["totals"]
    window = summary["window"]
    lines = [
        "# Three weeks of agent history -- SYNTHETIC",
        "",
        f"> {SYNTHETIC_NOTE}",
        "",
        f"Window **{window['start']} .. {window['end']}** ({window['days']} days), "
        f"seed `{summary['seed']}`, priced with `{summary['price_sheet']['path']}` "
        f"(simulated = {str(summary['price_sheet']['simulated']).lower()}).",
        "",
        "## Headline",
        "",
        "| | |",
        "| --- | --- |",
        f"| Coding sessions | {totals['sessions']} |",
        f"| Requests logged | {totals['requests']} |",
        f"| Requests routed to the cheap model | {totals['cheap_requests']} "
        f"({100.0 * totals['cheap_requests'] / totals['requests']:.0f}%) |",
        f"| Input / output / cached tokens | {totals['input_tokens']:,} / "
        f"{totals['output_tokens']:,} / {totals['cached_input_tokens']:,} |",
        f"| Same traffic, all on the strong model | ${totals['all_strong_usd']:.4f} |",
        f"| Same traffic, the mix the router chose | ${totals['actual_mix_usd']:.4f} |",
        f"| **List-price saving** | **${totals['saving_usd']:.4f} "
        f"({totals['saving_pct']:.1f}%)** |",
        "",
        "## By week",
        "",
        "| week | sessions | requests | switches | all strong | actual mix | saving |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for week in summary["weeks"]:
        lines.append(
            f"| {week['week']} | {week['sessions']} | {week['requests']} | "
            f"{week['switches']} | ${week['all_strong_usd']:.4f} | "
            f"${week['actual_mix_usd']:.4f} | ${week['saving_usd']:.4f} "
            f"({week['saving_pct']:.1f}%) |"
        )

    lines += [
        "",
        "## Every session",
        "",
        "| date | task | reqs | switches | all strong | actual mix | saving | result |",
        "| --- | --- | ---: | ---: | ---: | ---: | ---: | --- |",
    ]
    for session in summary["sessions"]:
        lines.append(
            f"| {session['date']} | {session['task']} | {session['requests']} | "
            f"{session['switches']} | ${session['all_strong_usd']:.4f} | "
            f"${session['actual_mix_usd']:.4f} | ${session['saving_usd']:.4f} | "
            f"{session['result']} |"
        )

    lines += [
        "",
        "## What the router decided, and why",
        "",
        "| reason | requests |",
        "| --- | ---: |",
    ]
    for reason, count in totals["decisions"].items():
        lines.append(f"| {reason} | {count} |")

    lines += [
        "",
        "## Honest limits",
        "",
        "- **Synthetic.** No request here was sent to a model. The tasks, the token",
        "  counts and the outcomes are invented by `demo/make_history.py`.",
        "- **Simulated prices.** `prices.simulated.toml` declares `simulated = true`, so",
        "  every amount above is stamped `SIMULATED PRICES, NOT REAL SAVINGS` wherever",
        "  `tamias report` prints it. The rates are made up; the arithmetic is the real",
        "  `tamias.pricing.compute_cost`.",
        "- **List prices, not a bill.** The saving is the gap between pricing the same",
        "  tokens on the strong model and pricing them on the model that answered. It is",
        "  not money that was spent, and not a measurement of quality.",
        "- **The history does not prove quality.** `result` is a field in this script, not",
        "  a test run. Nothing here shows the cheap model did the work well.",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help="output directory")
    parser.add_argument("--days", type=int, default=21, help="window length in days")
    parser.add_argument("--seed", type=int, default=7, help="RNG seed; same seed, same data")
    parser.add_argument(
        "--end",
        type=date.fromisoformat,
        default=date.today(),
        help="last day of the window, YYYY-MM-DD (default: today)",
    )
    parser.add_argument("--prices", type=Path, default=DEFAULT_PRICES, help="price sheet")
    args = parser.parse_args(argv)

    if args.days < 1:
        parser.error("--days must be at least 1")

    sheet = load_price_sheet(args.prices)
    rows, summary = build_history(args.end, args.days, args.seed, sheet)

    args.out.mkdir(parents=True, exist_ok=True)
    db_path = args.out / "agent-3weeks.db"
    json_path = args.out / "agent-3weeks.json"
    md_path = args.out / "SUMMARY.md"

    write_log(db_path, rows, sheet)
    json_path.write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")
    md_path.write_text(render_summary_markdown(summary), encoding="utf-8")

    totals = summary["totals"]
    print(f"make_history: wrote {db_path} ({totals['requests']} requests)")
    print(f"make_history: wrote {json_path}")
    print(f"make_history: wrote {md_path}")
    print(f"make_history: window {summary['window']['start']} .. {summary['window']['end']}")
    print(
        f"make_history: {totals['sessions']} sessions, {totals['requests']} requests, "
        f"{totals['switches']} switches, {totals['cheap_requests']} on the cheap model"
    )
    print(
        f"make_history: all strong ${totals['all_strong_usd']:.4f}, actual mix "
        f"${totals['actual_mix_usd']:.4f}, saving ${totals['saving_usd']:.4f} "
        f"({totals['saving_pct']:.1f}%)"
    )
    print("make_history: SYNTHETIC DATA, SIMULATED PRICES, NOT REAL SAVINGS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
