"""Pick models out of the public OpenRouter catalogue and price them.

Two jobs, and they are deliberately separable:

* ``--emit-toml ID [ID ...]`` writes a tamias price sheet for the named models.
  The conversion lives in :func:`to_toml_entry`, which is a pure function of one
  model dict, so it is tested without opening a socket.
* with no ``--emit-toml``, it prints the whole catalogue grouped by provider, so
  you can read prices before choosing anything.

The model list is public and needs no key::

    .venv/bin/python demo/pick_models.py
    .venv/bin/python demo/pick_models.py --emit-toml nvidia/nemotron-3-ultra-550b-a55b:free

A model is kept only when it can actually run this demo: ``supported_parameters``
must list ``tools`` (the task needs tool calls) and both prices must be greater
than zero.  Free models are therefore excluded on purpose -- they are real and
they cost nothing, which makes every saving in this demo exactly zero.  See
demo/RUNBOOK.md.
"""

from __future__ import annotations

import argparse
import json
import sys
import urllib.error
import urllib.request
from datetime import date
from typing import Any

MODELS_URL = "https://openrouter.ai/api/v1/models"
TOKENS_PER_MILLION = 1_000_000
NO_CACHE_DISCOUNT = "no cache discount known"


class PickError(RuntimeError):
    """Anything that stops the catalogue being read or priced."""


# --------------------------------------------------------------------------
# Pure helpers.  No network, no clock, no globals: these are the tested parts.
# --------------------------------------------------------------------------


def supports_tools(model: dict[str, Any]) -> bool:
    """True when the model advertises tool/function calling."""
    params = model.get("supported_parameters")
    return isinstance(params, list) and "tools" in params


def prices(model: dict[str, Any]) -> tuple[float, float]:
    """``(prompt, completion)`` in USD per token, as floats.

    OpenRouter publishes these as decimal *strings* ("0.000003"), so they are
    parsed rather than read as numbers.  A missing or unparseable price is 0.0,
    which then fails the ``> 0`` filter instead of crashing the run.
    """
    pricing = model.get("pricing")
    if not isinstance(pricing, dict):
        return 0.0, 0.0
    return _rate(pricing.get("prompt")), _rate(pricing.get("completion"))


def is_priceable(model: dict[str, Any]) -> bool:
    """A model this demo can run and can actually spend money on."""
    prompt, completion = prices(model)
    return supports_tools(model) and prompt > 0 and completion > 0


def provider_of(model_id: str) -> str:
    """The part of ``vendor/name`` before the slash, or the whole id if absent."""
    head, sep, _ = model_id.partition("/")
    return head if sep else model_id


def to_toml_entry(model: dict[str, Any]) -> str:
    """One model's price sheet table, as TOML text.

    Rates are per token on OpenRouter and per million tokens in tamias, so every
    rate is multiplied by 1e6.  ``cached_input`` uses ``input_cache_read`` when
    the catalogue publishes one; otherwise it falls back to the input rate,
    which is what the fallback is allowed to assume: no discount is better known
    than no discount claimed, and the assumption is written into the file.

    Pure: same dict in, same string out, no clock and no network.
    """
    model_id = model.get("id")
    if not isinstance(model_id, str) or not model_id:
        raise PickError("model has no id")

    prompt, completion = prices(model)
    pricing = model.get("pricing") if isinstance(model.get("pricing"), dict) else {}
    cache_read = _rate(pricing.get("input_cache_read"))
    if cache_read > 0:
        cached_input = cache_read
        comment = ""
    else:
        cached_input = prompt
        comment = f"  # {NO_CACHE_DISCOUNT}"

    # Model ids carry "/" and ":", so the key is quoted: TOML bare keys allow
    # only letters, digits, "_" and "-".
    return (
        f'["{model_id}"]\n'
        f"input = {_rate_toml(prompt * TOKENS_PER_MILLION)}\n"
        f"output = {_rate_toml(completion * TOKENS_PER_MILLION)}\n"
        f"cached_input = {_rate_toml(cached_input * TOKENS_PER_MILLION)}{comment}\n"
        f"cache_write = 0.0\n"
    )


def to_toml_sheet(models: list[dict[str, Any]], when: str | None = None) -> str:
    """A whole price sheet: a top-level ``date`` then one table per model."""
    stamp = when if when is not None else date.today().isoformat()
    header = (
        "# Price sheet generated by demo/pick_models.py from the public\n"
        "# OpenRouter catalogue.  Rates are USD per 1,000,000 tokens.\n"
        "#\n"
        "# cache_write is 0.0 on purpose: an OpenAI-style upstream carries no\n"
        "# cache-write token count, so a nonzero rate would leave every request\n"
        "# UNKNOWN rather than priced.\n"
        "\n"
        f'date = "{stamp}"\n'
    )
    return header + "\n" + "\n".join(to_toml_entry(model) for model in models)


# --------------------------------------------------------------------------
# Network and presentation.
# --------------------------------------------------------------------------


def fetch_models(url: str = MODELS_URL, timeout: float = 30.0) -> list[dict[str, Any]]:
    """GET the public model list.  No key, no auth header, one request."""
    request = urllib.request.Request(url, headers={"Accept": "application/json"})
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            payload = json.loads(response.read().decode("utf-8"))
    except urllib.error.URLError as exc:
        raise PickError(f"could not read {url}: {exc.reason}") from exc
    except (TimeoutError, json.JSONDecodeError) as exc:
        raise PickError(f"could not read {url}: {exc}") from exc

    data = payload.get("data") if isinstance(payload, dict) else None
    if not isinstance(data, list):
        raise PickError(f"{url} returned no `data` list")
    return [model for model in data if isinstance(model, dict)]


def print_table(models: list[dict[str, Any]]) -> None:
    """Print the priceable models, grouped by provider then cheapest first."""
    priceable = [model for model in models if is_priceable(model)]
    if not priceable:
        print("no model in the catalogue both supports tools and costs something")
        return

    priceable.sort(key=lambda model: (provider_of(str(model.get("id", ""))), prices(model)[0]))

    header = f"{'id':<58} {'in $/1M':>9} {'out $/1M':>9} {'context':>9}"
    print(header)
    print("-" * len(header))

    provider = None
    for model in priceable:
        model_id = str(model.get("id", ""))
        current = provider_of(model_id)
        if current != provider:
            provider = current
            print(f"{current}:")
        prompt, completion = prices(model)
        context = model.get("context_length")
        print(
            f"  {model_id:<56} {prompt * TOKENS_PER_MILLION:>9.4f} "
            f"{completion * TOKENS_PER_MILLION:>9.4f} {str(context or '?'):>9}"
        )

    print()
    print(f"{len(priceable)} of {len(models)} models support tools and cost something")


# --------------------------------------------------------------------------
# Internals.
# --------------------------------------------------------------------------


def _rate(value: Any) -> float:
    """USD per token, from whatever the catalogue published."""
    if isinstance(value, bool) or not isinstance(value, int | float | str):
        return 0.0
    try:
        return float(value)
    except ValueError:
        return 0.0


def _rate_toml(rate: float) -> str:
    """A rate as TOML text, always a float so the sheet reads like the others."""
    return repr(float(rate))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--emit-toml",
        nargs="+",
        metavar="ID",
        help="print a price sheet for these model ids instead of the table",
    )
    args = parser.parse_args(argv)

    try:
        models = fetch_models()
    except PickError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    if args.emit_toml:
        by_id = {str(model.get("id")): model for model in models}
        chosen = []
        for model_id in args.emit_toml:
            model = by_id.get(model_id)
            if model is None:
                print(f"error: no such model in the catalogue: {model_id}", file=sys.stderr)
                return 1
            chosen.append(model)
        sys.stdout.write(to_toml_sheet(chosen))
        return 0

    print_table(models)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
